@host=https://localhost:5001
GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NzZhODA0My02OGM5LTRjMmUtODQwMS0wNzhmMGY5NmJkMzYiLCJqdGkiOiJkNzMwOTUyNy1iNzJlLTRmOWEtYjIzOS1jNjczMjQyZDU4ZjEiLCJnaXZlbl9uYW1lIjoidGVzdCIsImZhbWlseV9uYW1lIjoidGVzdCIsImV4cCI6MTY2MTQ1NjcwMCwiaXNzIjoiRGlubmVyIEFwaSJ9.HSbQIrGzQx27bZxpMLPZFIjmABH2QjkzSBqK6bqi20U